[package]
name = "bdd"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
murmur3 = "0.5.1"
protocolo = { path = "../protocolo"}
seguridad = { path = "../seguridad"}
rand = "0.8.4"
rustls = "0.20.0"
rustls-pemfile = "1.0"