[package]
name = "interfaz"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"
walkers = "0.32.0"
rand = "0.8.5"
geo-types = { version = "0.7" }
protocolo = { path = "../protocolo" }
cliente-servidor = { path = "../cliente-servidor" }
chrono = "0.4.38"